name: Clone public repo

on:
  push:
    branches:
      - main

jobs:
  clone-public-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo actuel
        uses: actions/checkout@v3

      - name: Cloner un dépôt public via HTTPS
        run: |
          git clone https://github.com/djamelboubred/django_econet.git temp_repo
          ls temp_repo
