name: Clone public repo

on:
  push:
    branches:
      - main

jobs:
  clone-public-repo:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo actuel
        uses: actions/checkout@v3

      - name: Cloner un dépôt public via HTTPS
        run: |
          git clone https://github.com/djamelboubred/django_econet.git temp_repo
          ls temp_repo
      - name: Copier dans une branche
        run: |
          shopt -s dotglob
          cp -r temp_repo/* ./
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout -b synced-from-django-econet
          git add .
          git commit -m "Sync dépôt django_econet"
          git push origin synced-from-django-econet --force
